### ISSUE TITLE
Crash on item drag

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/checklistview#10]
https://app.tracepot.com/app/321/release/0a6c096900000141

**Comment by d-faure** [comment]
As requested, I also tested with the CheckListView demo and got the same result with the list is displayed as a real list (with its movable handlers), and as soon as I try to use one of them to reorder the items.
Here's the kind of log I could get:
	02-29 07:50:06.503 E/AndroidRuntime(11884): FATAL EXCEPTION: main
	02-29 07:50:06.503 E/AndroidRuntime(11884): java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.addViewInner(ViewGroup.java:3448)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.addView(ViewGroup.java:3319)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.addView(ViewGroup.java:3264)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at it.feio.android.checklistview.a.b.c(Unknown Source)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at it.feio.android.checklistview.a.b.b(Unknown Source)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at it.feio.android.checklistview.a.b.onDrag(Unknown Source)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.View.dispatchDragEvent(View.java:16636)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1263)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1200)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at it.feio.android.checklistview.d.a.dispatchDragEvent(Unknown Source)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewGroup.dispatchDragEvent(ViewGroup.java:1212)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewRootImpl.handleDragEvent(ViewRootImpl.java:4323)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewRootImpl.access$1100(ViewRootImpl.java:103)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3408)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.os.Handler.dispatchMessage(Handler.java:107)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.os.Looper.loop(Looper.java:194)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at android.app.ActivityThread.main(ActivityThread.java:5391)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at java.lang.reflect.Method.invokeNative(Native Method)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at java.lang.reflect.Method.invoke(Method.java:525)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	02-29 07:50:06.503 E/AndroidRuntime(11884): 	at dalvik.system.NativeStart.main(Native Method)
	02-29 07:50:06.543 E/AppErrorDialog(745): Failed to get ILowStorageHandle instance

**Comment by federicoiosue** [comment]
What's your device and OS @d-faure?

**Comment by d-faure** [comment]
This is an HTC Desire 310 running Android 4.2.2

**Comment by federicoiosue** [comment]
Now should work.

I had to disable animations on Android < KitKat due to something that seems to be an intrinsic problem with Android framework itself that has been solved on later versions.
