### ISSUE TITLE
Interval between touch and start move items is too short

### ISSUE THREAD

**Issue by ssergiienko** [federicoiosue/checklistview#12]
I will try to explain why this is an issue.
I am a left-handed person :) When i scroll CheckList up|down holding my phone in left hand it's too easy accidentally start to move list items with my thumb. If this "hold to move" interval would be a little longer, that can significantly reduce number of such errors.

**Comment by federicoiosue** [comment]
That's a default Android framework delay, so I'm supposing this issue touches you in every app
