### ISSUE TITLE
Can drag but can't drop

### ISSUE THREAD

**Issue by koichirose** [federicoiosue/checklistview#22]
I'm trying to implement this in my app.

This is the layout I'm using (in reality, it contains more stuff but I've reduced it to this and it still doesn't drop):
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:float="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">

            <EditText
                android:id="@+id/editReminderContent"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </LinearLayout>
    </ScrollView>
</LinearLayout>
```

Debug log says:
```
...
V/ChecklistViewItemOnDragListener: Dragging item. Action: 1
I/ViewRootImpl[EditReminderActivity]: Reporting drop result: false
V/ChecklistViewItemOnDragListener: Dragging item. Action: 4
...
```

Behavior: I can create and delete items, then I can drag them but when I drop them they return to their original position.

Can post code if needed (although it's very similar to the one found [here](https://github.com/federicoiosue/checklistview/blob/develop/checklistview_demo/src/main/java/it/feio/android/checklistview/demo/MainActivity.java#L105)

**Comment by federicoiosue** [comment]
Related to #20

**Comment by yangchunhui** [comment]
why? i have the same question

**Comment by federicoiosue** [comment]
@yangchunhui you're testing on Android 7 too? In that case is a known problem that affects also other apps using this library.

**Comment by yangchunhui** [comment]
sorry，i not use this  library, i listener drag event in different app,i want to receive DragEvent.ACTION_DROP,but not work, i can receive DragEvent.ACTION_DRAG_STARTED and DragEvent.ACTION_DRAG_ENDED only, i using android 9. can you give some advise
