### ISSUE TITLE
Checklist improvement idea - add checklist anywhere

### ISSUE THREAD

**Issue by RiddleDude** [federicoiosue/CheckListView#6]
### Idea
Possibility to add checklist anywhere in regular note.
Currently you can **transform** regular note into checklist by clicking ``Enable checklist``. This adds check-box to any row in the note. What if you could enable it *on demand*, e.g. final note would be:
> Ingredients for chocolate cake: (now you make a list)
> [ ] Chocolate
> [x] Cake
> Recipe: (make a list again)
> [ ] Open chocolate
> [ ] Make cake

I actually haven't seen an app that could do this. There usually is just ``create list`` or ``create note ``, this hybrid functionality seems a nice touch

[Original link](https://github.com/federicoiosue/Omni-Notes/issues/211)

**Comment by federicoiosue** [comment]
It's a nice idea but it's not the purpose of the library.
Being into your request some logic that just human decisions could determine it would actually be a better idea to just use something markup-based (html, markdown) to achieve that.
